name: ys_sign
description: 用于原神的签到脚本
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.4.0
  crypto: any
  path: ^1.9.1
dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
